// lib/audioMappings.ts - Mapping des lettres/mots vers les noms de fichiers audio

export const letterAudioMappings: { [key: string]: string } = {
  // Lettres de base - vous pouvez utiliser n'importe quel nom
  'ا': 'alif',
  'ب': 'ba',
  'ت': 'ta',
  'ث': 'tha',
  'ج': 'jim',
  'ح': 'ha',
  'خ': 'kha',
  'د': 'dal',
  'ذ': 'dhal',
  'ر': 'ra',
  'ز': 'zay',
  'س': 'sin',
  'ش': 'shin',
  'ص': 'sad',
  'ض': 'dad',
  'ط': 'ta_emphatic',
  'ظ': 'dha_emphatic',
  'ع': 'ayn',
  'غ': 'ghayn',
  'ف': 'fa',
  'ق': 'qaf',
  'ك': 'kaf',
  'ل': 'lam',
  'م': 'mim',
  'ن': 'nun',
  'ه': 'ha_final',
  'و': 'waw',
  'ي': 'ya',
  'ء': 'hamza',
  'ة': 'ta_marbuta'
};

export const vowelAudioMappings: { [key: string]: string } = {
  // Lettres avec voyelles - format: lettre_voyelle
  'اَ': 'alif_with_fatha',
  'اُ': 'alif_with_damma',
  'اِ': 'alif_with_kasra',
  'بَ': 'ba_with_fatha',
  'بُ': 'ba_with_damma',
  'بِ': 'ba_with_kasra',
  'تَ': 'ta_with_fatha',
  'تُ': 'ta_with_damma',
  'تِ': 'ta_with_kasra',
  'ثَ': 'tha_with_fatha',
  'ثُ': 'tha_with_damma',
  'ثِ': 'tha_with_kasra',
  'جَ': 'jim_with_fatha',
  'جُ': 'jim_with_damma',
  'جِ': 'jim_with_kasra',
  'حَ': 'ha_with_fatha',
  'حُ': 'ha_with_damma',
  'حِ': 'ha_with_kasra',
  'خَ': 'kha_with_fatha',
  'خُ': 'kha_with_damma',
  'خِ': 'kha_with_kasra',
  'دَ': 'dal_with_fatha',
  'دُ': 'dal_with_damma',
  'دِ': 'dal_with_kasra',
  'ذَ': 'dhal_with_fatha',
  'ذُ': 'dhal_with_damma',
  'ذِ': 'dhal_with_kasra',
  'رَ': 'ra_with_fatha',
  'رُ': 'ra_with_damma',
  'رِ': 'ra_with_kasra',
  'زَ': 'zay_with_fatha',
  'زُ': 'zay_with_damma',
  'زِ': 'zay_with_kasra',
  'سَ': 'sin_with_fatha',
  'سُ': 'sin_with_damma',
  'سِ': 'sin_with_kasra',
  'شَ': 'shin_with_fatha',
  'شُ': 'shin_with_damma',
  'شِ': 'shin_with_kasra',
  'صَ': 'sad_with_fatha',
  'صُ': 'sad_with_damma',
  'صِ': 'sad_with_kasra',
  'ضَ': 'dad_with_fatha',
  'ضُ': 'dad_with_damma',
  'ضِ': 'dad_with_kasra',
  'طَ': 'ta_emphatic_with_fatha',
  'طُ': 'ta_emphatic_with_damma',
  'طِ': 'ta_emphatic_with_kasra',
  'ظَ': 'dha_emphatic_with_fatha',
  'ظُ': 'dha_emphatic_with_damma',
  'ظِ': 'dha_emphatic_with_kasra',
  'عَ': 'ayn_with_fatha',
  'عُ': 'ayn_with_damma',
  'عِ': 'ayn_with_kasra',
  'غَ': 'ghayn_with_fatha',
  'غُ': 'ghayn_with_damma',
  'غِ': 'ghayn_with_kasra',
  'فَ': 'fa_with_fatha',
  'فُ': 'fa_with_damma',
  'فِ': 'fa_with_kasra',
  'قَ': 'qaf_with_fatha',
  'قُ': 'qaf_with_damma',
  'قِ': 'qaf_with_kasra',
  'كَ': 'kaf_with_fatha',
  'كُ': 'kaf_with_damma',
  'كِ': 'kaf_with_kasra',
  'لَ': 'lam_with_fatha',
  'لُ': 'lam_with_damma',
  'لِ': 'lam_with_kasra',
  'مَ': 'mim_with_fatha',
  'مُ': 'mim_with_damma',
  'مِ': 'mim_with_kasra',
  'نَ': 'nun_with_fatha',
  'نُ': 'nun_with_damma',
  'نِ': 'nun_with_kasra',
  'هَ': 'ha_final_with_fatha',
  'هُ': 'ha_final_with_damma',
  'هِ': 'ha_final_with_kasra',
  'وَ': 'waw_with_fatha',
  'وُ': 'waw_with_damma',
  'وِ': 'waw_with_kasra',
  'يَ': 'ya_with_fatha',
  'يُ': 'ya_with_damma',
  'يِ': 'ya_with_kasra',
  'ءَ': 'hamza_with_fatha',
  'ءُ': 'hamza_with_damma',
  'ءِ': 'hamza_with_kasra',
  'ةَ': 'ta_marbuta_with_fatha',
  'ةُ': 'ta_marbuta_with_damma',
  'ةِ': 'ta_marbuta_with_kasra'
};

export const wordAudioMappings: { [key: string]: string } = {
  // Mots des exercices - noms personnalisés
  'في': 'word_fi',
  'من': 'word_min',
  'قل': 'word_qul',
  'هو': 'word_huwa',
  'ما': 'word_ma',
  'أن': 'word_an',
  'لم': 'word_lam',
  'كل': 'word_kull',
  'ثم': 'word_thumma',
  'هل': 'word_hal',
  'عن': 'word_an_preposition',
  'به': 'word_bihi',
  'له': 'word_lahu',
  'رب': 'word_rabb',
  'هم': 'word_hum',
  'نا': 'word_na',
  'كم': 'word_kam',
  'أي': 'word_ayy',
  'نور': 'word_nur',
  'عبد': 'word_abd',
  'نار': 'word_nar',
  'يدع': 'word_yadu',
  'فوز': 'word_fawz',
  'ملك': 'word_malik',
  'نهر': 'word_nahr',
  'قمر': 'word_qamar',
  'غيب': 'word_ghayb',
  'رسل': 'word_rusul',
  'نفس': 'word_nafs',
  'ضر': 'word_darr',
  'صمت': 'word_samt',
  'خير': 'word_khayr',
  'علم': 'word_ilm',
  'قلب': 'word_qalb',
  'خلق': 'word_khalq',
  'غفر': 'word_ghafara',
  'سجد': 'word_sajada',
  'عدة': 'word_idda',
  'خوف': 'word_khawf',
  'صدق': 'word_sadaqa',
  'كفر': 'word_kafara',
  'نصر': 'word_nasr',
  'سؤل': 'word_sual',
  'أمر': 'word_amr',
  'يئس': 'word_yaisa',
  'وَرَقٌ': 'word_waraq',
  'قَلَمٌ': 'word_qalam',
  'مَلَكٌ': 'word_malak',
  'بَشَرٌ': 'word_bashar',
  'جَبَلٌ': 'word_jabal',
  'بَقَرٌ': 'word_baqar',
  'ثَمَرٌ': 'word_thamar',
  'حَجَرٌ': 'word_hajar',
  'لَبَنٌ': 'word_laban',
  'وَلَدٌ': 'word_walad',
  'فَمٌ': 'word_fam',
  'رَجُلٌ': 'word_rajul',
  'سَمَكٌ': 'word_samak',
  'يَدٌ': 'word_yad',
  'زَمَنٌ': 'word_zaman',
  // Ajoutez tous les autres mots...
};

// Fonction pour obtenir le nom du fichier audio
export function getAudioFileName(text: string, type: 'letter' | 'vowel' | 'word'): string {
  switch (type) {
    case 'letter':
      return letterAudioMappings[text] || text;
    case 'vowel':
      return vowelAudioMappings[text] || text;
    case 'word':
      return wordAudioMappings[text] || text;
    default:
      return text;
  }
}